branch-defaults:
  master:
    environment: Demo2-env
#    environment: $CIRCLE_BRANCH-my-application
global:
  application_name: demo2
#  default_ec2_keyname: XXXXXX
#  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: ap-northeast-2
  sc: git